<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Claim Your $5 Offer</title>
<style type="text/css">
body{margin:0;}
</style>
</head>
<body>
<table width="600" cellspacing="0" cellpadding="0" style="width:600px; margin:auto;">
  <tr>
    <td bgcolor="#282625">
      <table width="100%">
        <tr>
          <td style="font-size:0;padding-left:20px;"><a href="https://munchado.com/" title="MunchAdo.com" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH;?>logo-munch.png" alt="munchado" border="0"></a></td>
          <td>
            <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
              <td align="right" style="font-family:Arial, Helvetica, sans-serif; font-size:13px;color:#ffffff;">Follow Us</td>
              <td width="29" align="right"><a href="http://blog.munchado.com" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH;?>blog_icon.png" alt="Blog icon" width="20" height="20" border="0"></a></td>
              <td width="25" align="right"><a target="_blank" href="https://www.facebook.com/munchado"><img src="<?php echo TEMPLATE_IMG_PATH;?>fb_icon.png" alt="Fb Icon" width="20" height="20" border="0"></a></td>
              <td width="25" align="right"><a target="_blank" href="https://twitter.com/Munch_Ado"><img src="<?php echo TEMPLATE_IMG_PATH;?>twitter_icon.png" alt="Twitter Icon" width="20" height="20" border="0"></a></td>
              <td width="25" align="right"><a target="_blank" href="http://pinterest.com/munchado/"><img src="<?php echo TEMPLATE_IMG_PATH;?>pin_icon.png" alt="Pin Interest Icon" width="20" height="20" border="0"></a></td>
              <td width="25" align="right"><a target="_blank" href="https://plus.google.com/b/106525625756971589805/106525625756971589805/posts"><img src="<?php echo TEMPLATE_IMG_PATH;?>gplus.png" alt="Email Icon" width="20" height="20" hspace="0" border="0"></a></td>
              <td width="25" align="right" style="padding-right:20px;"><a target="_blank" href="https://instagram.com/munchado/"><img src="<?php echo TEMPLATE_IMG_PATH;?>isnagram_icon.png" alt="instagram" width="20" height="20" hspace="0" border="0"></a></td>
            </tr>
          </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="font-size:0;background:#7f5538;"><img src="<?php echo TEMPLATE_IMG_PATH;?>banner2.jpg" alt="$10 off" width="100%" border="0" style="display:block"></td>
  </tr>

      <?php echo $this->content; ?>

   <tr>
    <td bgcolor="#ececed">
      <p style="margin:0; font-family:Arial, Helvetica, sans-serif; padding-left:20px; padding-top:14px;padding-bottom:21px;color:#666666; font-size:12px; line-height:18px">245 5th Avenue Suite 1002, New York, NY 10016<br/><br/>
      Copyright 2014. Munch Ado LLC. All rights reserved.<br/>
      <a style="color:#ff8208; text-decoration:none; font-weight:bold;" href="<?php echo $this->terms_url; ?>">Terms</a> | <a style="color:#ff8208; 
text-decoration:none; font-weight:bold;" href="<?php echo $this->privacy_url; ?>">Privacy Policy</a> | <a style="color:#ff8208; font-weight:bold; text-decoration:none;" 
href="<?php echo $this->support_url; ?>">FAQs & Customer support</a></p>
    </td>
  </tr>
  <tr>
    <td bgcolor="#45484a" style="font-size:11px;font-family:Arial, Helvetica, sans-serif;color:#FFFFFF;padding-left:20px;padding-right:20px;padding-top:15px;padding-bottom:15px;">To make sure our email updates are delivered to your inbox, please add <a style="color:#ff8208; text-decoration:none;" href="mailto:wecare@munchado.com"><strong>WeCare@MunchAdo.com</strong></a> to your email Address Book.</td>
  </tr>
</table>
</body>
</html>