<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
 <style type="text/css">
  @-ms-viewport {width: device-width;}
           @media screen and (max-device-width: 400px), screen and (max-width: 400px) {
           img[id="dv1"], img[id="dv2"] {display: none !important;}
           }
body > a:any-link {
    color: #f31858;
	text-decoration:none !important;
	 border-color:#fff !important;
	  border-bottom-color: #fff !important;
}
 </style>
 
 
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Munch Ado Career</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding-left: 5px;">
 <table align="center" cellpadding="0" cellspacing="0"  style="border-collapse: collapse; width:100%;  max-width:650px;   font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px">
 	<tr>
    	<td style="background:#282625">
        	<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;" >
            	
                <tr>
                	<td width="6%" height="10"></td>
                    <td width="40%" height="10" align="left" valign="middle"></td>
                    <td width="48%" height="10" align="right" valign="middle"></td>
                    <td width="6%" height="10"></td>
                </tr>
                
                
            	<tr>
                	<td width="6%"></td>
                    <td width="40%" align="left" valign="middle">
                    	<a href="https://munchado.com/" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/dine-more/bravvura-email/munchado-logo.jpg" style="line-height:0" alt="Munch Ado"  /></a>		
                    
                    </td>
                    <td width="48%" align="right" valign="middle">
                    	<table align="right" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:222px;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;">
                        	<tr>
                            	<td width="70" style="color:#ffffff; font-size:14px; line-height:18px;">Follow Us</td>
                                <td width="38" align="center"><a href="https://www.linkedin.com/company/munch-ado" target="_blank" style="line-height:0;"><img src="https://s3-us-west-2.amazonaws.com/dine-more/bravvura-email/munchado_linked_logo.jpg" alt="linked in" /></a></td>
                    	
                        		<td width="38" align="center"><a href="https://www.facebook.com/munchado" target="_blank" style=" line-height:0;"><img src="https://s3-us-west-2.amazonaws.com/dine-more/bravvura-email/munchado_facebook_logo.jpg" alt="facebook" /></a></td>
                        		<td width="38" align="center"><a href="https://twitter.com/Munch_Ado" target="_blank" style="line-height:0;"><img src="https://s3-us-west-2.amazonaws.com/dine-more/bravvura-email/munchado_twitter_logo.jpg" alt="twitter" /></a></td>
                        		<td width="38" align="center"><a href="http://instagram.com/munchado" target="_blank"  style="line-height:0;"><img src="https://s3-us-west-2.amazonaws.com/dine-more/bravvura-email/munchado_instagram_logo.jpg" alt="instagram" /></a></td>		
                        	</tr>
                    	</table>
                    </td>
                    <td width="6%"></td>
                </tr>
                <tr>
                	<td width="6%" height="10"></td>
                    <td width="40%" height="10" align="left" valign="middle"></td>
                    <td width="48%" height="10" align="right" valign="middle"></td>
                    <td width="6%" height="10"></td>
                </tr>
        
        	</table>
        </td>
    </tr>
    
    <tr>
    	<td style="background:#ffffff">
        	<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;" >
            	<tr>
                	<td width="6%"></td>
                	<td width="88%">
                    	<?php echo $this->content; ?>
                    </td>
                    <td width="6%"></td>
                </tr>
            </table>
        
        </td>
    
    </tr>
    
    
    <tr>
    	<td style="background:#f0f0f0">
        	<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;" >
            	<tr>
                	<td width="6%"></td>
                	<td width="88%">
                    	<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;">	
                        	<tr><td height="18"></td></tr>
                            <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:14px;">245 5th Avenue Suite 1002, New York, NY 10016</td></tr>
                            <tr><td height="6"></td></tr>
                            <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:14px; line-height:24px">Copyright 2014. Munch Ado LLC. All rights reserved.</td></tr>
                            <tr><td height="8"></td></tr>
                            <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:14px; line-height:24px">
                            <a href="<?php echo $this->terms_url; ?>" target="_blank" style="text-decoration:none; color:#ff8208; outline:none; font-weight:bold">Terms</a>&nbsp;|&nbsp;<a href="<?php echo $this->privacy_url; ?>" target="_blank" style="text-decoration:none; color:#ff8208; outline:none; font-weight:bold">Privacy Policy</a>&nbsp;|&nbsp;<a href="<?php echo $this->support_url; ?>" target="_blank" style="text-decoration:none; color:#ff8208; outline:none; font-weight:bold">FAQs &amp; Customer support</a></td></tr>
                            <tr><td height="8"></td></tr>
                           
                        </table>
                    </td>
                    <td width="6%"></td>
                </tr>
            </table>
        
        </td>
    
    </tr>
    <tr>
    	<td style="background:#45484a">
        	<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;" >
            	<tr>
                	<td width="6%"></td>
                	<td width="88%">
                    	<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;">	
                        	<tr><td height="8"></td></tr>
                            <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:12px; color:#ffffff; line-height:18px">To make sure our email updates are delivered to your inbox, please add  <a href="mailto:WeCare@MunchAdo.com" style="text-decoration:none; color:#ff8208; outline:none">WeCare@MunchAdo.com</a> to your email Address Book.</td></tr>
                            
                            <tr><td height="8"></td></tr>
                            
                        </table>
                    </td>
                    <td width="6%"></td>
                </tr>
            </table>
        
        </td>
    
    </tr>
    
 
 
 </table>
</body>
</html>