<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Munchado</title>
<style type="text/css">
body{margin:0;}
</style>
</head>
<body>
    <center>    
    <table width="600"  bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="margin-left:auto; margin-right:auto; margin-top:0;margin-bottom:0;">
        <tr>
            <td>
                <table width="100%" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="right" style="font-family:Arial, Helvetica, sans-serif; font-size:13px;">Follow Us</td>
                    <td width="29" align="right"><a href="http://blog.munchado.com" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH.'blog_icon.jpg';?>" alt="Blog icon" width="20" height="20" border="0"></a></td>
                    <td width="25" align="right"><a target="_blank" href="https://www.facebook.com/munchado"><img src="<?php echo TEMPLATE_IMG_PATH.'fb_icon.jpg';?>" alt="Fb Icon" width="20" height="20" border="0"></a></td>
                    <td width="25" align="right"><a target="_blank" href="https://twitter.com/Munch_Ado"><img src="<?php echo TEMPLATE_IMG_PATH.'twiter_icon.jpg';?>" alt="Twitter Icon" width="20" height="20" border="0"></a></td>
                    <td width="25" align="right"><a target="_blank" href="http://pinterest.com/munchado/"><img src="<?php echo TEMPLATE_IMG_PATH.'pin_icon.jpg'; ?>" alt="Pin Interest Icon" width="20" height="20" border="0"></a></td>
                    <td width="25" align="right"><a target="_blank" href="https://plus.google.com/b/106525625756971589805/106525625756971589805/posts"><img src="<?php echo TEMPLATE_IMG_PATH.'gplus.jpg'; ?>" alt="Email Icon" width="20" height="20" hspace="0" border="0"></a></td>
                    <td width="25" align="right" style="padding-right:0;"><a target="_blank" href="https://instagram.com/munchado/"><img src="<?php echo TEMPLATE_IMG_PATH.'isnagram_icon.png'; ?>" alt="instagram" width="20" height="20" hspace="0" border="0"></a></td>
                  </tr>
                  <tr>
                    <td colspan="6" height="5"></td>
                  </tr>
                </table>
            </td>
        </tr>
         <tr>
            <td bgcolor="#fd8207">
              <table width="100%" cellspacing="0" cellpadding="0">
                  <tr>
                     <td style="font-size:0;padding-left:10px;padding-top:5px;padding-bottom:5px">
                         <a href="<?php echo PROTOCOL.SITE_URL; ?>" target="_blank"><img src="<?php echo TEMPLATE_IMG_PATH.'emailer-munchlogo.gif';?>" width="210" alt="Munch Ado" border="0" style="display: block;" ></a></td>
                  </tr>
              </table>
            </td>
        </tr>
        <tr>
            <td>
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 20px; color: #666666; text-align:left">
                    <?php echo $this->content; ?>
                </table></td>
        </tr>
        <tr>
            <td><img src="<?php echo TEMPLATE_IMG_PATH.'Dottedborder.gif';?>" height="1" width="100%" alt="" style="display:block"></td>
      </tr>
      <tr>
        <td bgcolor="#ececed" style="padding-left:10px;padding-bottom:21px;padding-top:15px;padding-bottom:15px;text-align:left">
          <p style="margin:0;padding:0; font-family:Arial, Helvetica, sans-serif;color:#666666; font-size:12px; line-height:18px">245 5th Avenue Suite 1002, New York, NY 10016<br/><br/>
          Copyright 2014. Munch Ado LLC. All rights reserved.<br/>
          <a style="color:#ff8208; text-decoration:none; font-weight:bold;" href="<?php echo $this->terms_url; ?>">Terms</a> | <a style="color:#ff8208; 
    text-decoration:none; font-weight:bold;" href="<?php echo $this->privacy_url; ?>">Privacy Policy</a> | <a style="color:#ff8208; font-weight:bold; text-decoration:none;" 
    href="<?php echo $this->support_url; ?>">FAQs & Customer support</a></p>
        </td>
    </tr>
    <tr>
        <td bgcolor="#45484a" style="font-size:11px;font-family:Arial, Helvetica, sans-serif;color:#FFFFFF;padding-left:10px;padding-right:10px;padding-top:15px;padding-bottom:15px;text-align:left">To make sure our email updates are delivered to your inbox, please add <a style="color:#ff8208; text-decoration:none;" href="mailto:wecare@munchado.com"><strong>WeCare@MunchAdo.com</strong></a> to your email Address Book.</td>
    </tr>
    </table>
    </center>
</body>    
</html>