<?php echo $this->content; ?>

<tr>
    <td align="center" valign="top">
        <table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" style="width: 100%; max-width: 550px;">
            <tr>
                <td valign="top" align="center" style="padding: 20px; background: #f6f8f1;">
                    <table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" style="width: 100%; max-width: 490px;">
                        <tr>
                            <td style="font-size: .875em; font-family: Arial; color:#3d3a39;" align="center">Presented BY</td>
                        </tr>
                        <tr>
                            <td style="text-align:center;padding-bottom:10px;">
                                <a href="<?php echo WEB_HOST_URL; ?>" target="_blank">
                                    <img src="<?php echo TEMPLATE_IMG_PATH; ?>logo_munchado.png" alt="Munch Ado" style="border:0;max-width:100%;">
                                </a>
                            </td>
                        </tr>


                        <tr>
                            <td style="font-size: .875em; font-family: Arial; color:#3d3a39;" align="center">FOLLOW US</td>
                        </tr>
                        <tr>
                            <td style="padding-top: 19px;" align="center">
                                <span style="display: inline-block; width: auto; overflow: hidden; width: 100%; max-width: 275px;">
                                    <a href="https://www.facebook.com/munchado" target="_blank" style="display: inline-block;">
                                        <img src="<?php echo TEMPLATE_IMG_PATH; ?>facebook-icon.png" alt="Facebook" width="65" height="65" border="0">
                                    </a>
                                    <img id="dv1" src="<?php echo TEMPLATE_IMG_PATH; ?>devider.jpg" alt="" width="6">
                                    <a href="http://twitter.com/Munch_Ado" style="display: inline-block;">
                                        <img src="<?php echo TEMPLATE_IMG_PATH; ?>twitter-icon.png" alt="Twitter" width="65" height="65" border="0">
                                    </a>
                                    <img id="dv2" src="<?php echo TEMPLATE_IMG_PATH; ?>devider.jpg" alt="" width="6">
                                    <a href="http://www.instagram.com/munchado" target="_blank" style="display: inline-block;">
                                        <img src="<?php echo TEMPLATE_IMG_PATH; ?>instagram-icon.png" alt="Instagram" width="65" height="65" border="0">
                                    </a>
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" style="padding:25px 0 40px;">
                                <!--[if mso]>
                                  <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://www.munchadomag.com/" style="height:69px;v-text-anchor:middle;width:325px;" arcsize="9%" stroke="f" fillcolor="#d4d9c7">
                                     <w:anchorlock/>
                               <center>
                               <![endif]-->
                                <a href="http://www.munchadomag.com/" target="_blank" style="background-color:#d4d9c7;border-radius:6px;color:#45484a;display:inline-block;font-family:sans-serif;font-size:17px;font-weight:normal;padding-top:20px;padding-bottom:20px;text-align:center;text-decoration:none;width:100%;max-width:325px;-webkit-text-size-adjust:none;">VISIT THE MUNCH ADO MAG</a>
                                <!--[if mso]>
                                </center>
                                </v:roundrect>
                                <![endif]-->
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:center; padding-bottom:30px">
                                <a href="https://play.google.com/store/apps/details?id=com.munchado&hl=en" target="_blank">
                                    <img src="<?php echo TEMPLATE_IMG_PATH; ?>btn_googleplay.png" alt="Download it from google play" style="border:0;max-width:100%;"></a>
                                <a href="https://itunes.apple.com/us/app/munch-ado/id1024973395?ls=1&mt=8" target="_blank">
                                    <img src="<?php echo TEMPLATE_IMG_PATH; ?>btn_iphone.png" alt="Download it from apple store" style="border:0;max-width:100%;">
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td style="font-size: .938em; line-height: 1.250em; font-family: Arial; color:#3d3a39; text-align:left;" align="left">
                                <a style="text-decoration:none;color:#3d3a39;text-align:left;cursor:text;">245 5th Avenue Suite 1002, New York, NY 10016</a><br>
                                Copyright 2013-2015. Munch Ado LLC. All rights reserved.<br /><br />Toll Free: <a href="tel:1-888-345-1303" style="font-weight:bold;color:#3d3a39;text-decoration:none">1-888-345-1303</a>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding-top: 15px; font-size:15px; font-weight: bold; font-family: Arial;text-align:left;color:#3d3a39;">
                                <a href="<?php echo WEB_HOST_URL; ?>terms" target="_blank" style="text-decoration:none; outline: none; color: #ff8207;">Terms</a> | <a href="<?php echo WEB_HOST_URL; ?>privacy" target="_blank" style="text-decoration:none;outline: none; color: #ff8207;">Privacy Policy</a> | <a href="<?php echo WEB_HOST_URL; ?>support" target="_blank" style="text-decoration:none;outline: none; color: #ff8207;">FAQs &amp; Customer Support</a>
                            </td>
                        </tr>

                    </table>
                </td>
            </tr>
            <tr>
                <td style="background: #3d3a39; font-size:15px;color: #fff;line-height:20px; font-family: Arial;text-align:left;padding-left:30px;padding-right:30px;padding-top:20px;padding-bottom:20px;">To make sure our email updates are delivered to your inbox, please add <a href="mailto:wecare@munchado.com" style="text-decoration:none;color: #ff8207; font-weight: bold; outline: none;">WeCare@MunchAdo.com</a> to your email Address Book.
                </td>
            </tr>
        </table>
    </td>
</tr>
</table>
<!--[if (gte mso 9)|(IE)]>
        </td>
    </tr>
</table>
<![endif]--></body>
</html>   