
  <tr>
    <td>
      <p style="font-family:Arial, Helvetica, sans-serif; font-size:15px; color:#4b4b4b;padding-left:20px;padding-left:20px;padding-top:40px;padding-bottom:80px;padding-right:20px;line-height:20px;margin:0">
        How cool is <strong style="color:fd7d01"><?php echo $this->campaignName ;?></strong>, right?
        <br /><br />It&#8217;s clear you and we have similar interests and this is the 
        bringing of a beautiful friendship.<br /><br />We&#8217;re so excited to become 
        fast friends; we went ahead and created an account for you on <a href="http://munchado.com">MunchAdo.com</a>. 
        You have $10 waiting for you to spend at any of our partner restaurants or on any 
        of our curated lists and promotions.<br /><br />
        Your Login information is:<br />
        <strong>Email Address: <a style="color:#ff8208; text-decoration:none;" href="mailto:emailaddress@munchado.com"><?php echo $this->email ;?></a></strong>
        <br /><strong>Password: <span style="color:#ff8208;"><?php echo $this->password ;?></span></strong>
        <br>(Reset your password when you are login)
        <br /><br />We can&#8217;t wait to see what you do on the pages of Munch Ado! We hope you&#8217;ll 
        be ordering, reserving, reviewing, sharing and, of course, discovering!
        <br /><br />For now though, <br />We must bid you Munch Ado
        <br /><br />P.S. We&#8217;re not quite sure we caught your name or your location, 
        so please update your details when you log in to your account 
        (On the "My Details" tab under "My Munch Ado") to get the most out of Munch Ado.
      </p>
    </td>
  </tr>
 