
  <tr>
    <td>
      <p style="font-family:Arial, Helvetica, sans-serif; font-size:15px; color:#4b4b4b;padding-left:20px;padding-left:20px;padding-top:40px;padding-bottom:80px;padding-right:20px;line-height:20px;margin:0">
        Hey <strong style="color:fd7d01"><?php echo $this->userName ;?></strong>, 
        <br /><br />Nice job registering for <a style="color: #ff8208; text-decoration: none;" href="http://munchado.com">MunchAdo.com</a>. That&#8217;s probably the best decision you&#8217;ve made today – though we don&#8217;t know your life, so we could be wrong. 
        <br /><br />Anyway, in recognition of your fine-tuned decision-making you&#8217;ve earned $5 off your first order on <a href="http://munchado.com">MunchAdo.com</a>. 
        Next time you login to <a href="http://munchado.com">Munch Ado</a>, it&#8217;ll be waiting for you. Safe, secure, and under our protection - until you&#8217;re ready to discover some awesome restaurants, order tasty food and reserve reservations.
        <br /><br />For now though,<br />We must bid you Munch Ado
      </p>
    </td>
  </tr>
 