
  <tr>
    <td>
      <p style="font-family:Arial, Helvetica, sans-serif; font-size:15px; color:#4b4b4b;padding-left:20px;padding-left:20px;padding-top:40px;padding-bottom:80px;padding-right:20px;line-height:20px;margin:0">
        Hey <strong style="color:fd7d01"><?php echo $this->username ;?></strong>,
        <br /><br />Looks like you found another curated list by Munch Ado you like. 
        We&#8217;re more than happy to start sending you more recommendation from 
        "<?php echo $this->campaignName; ?>", but we&#8217;re sorry to say we can&#8217;t 
        credit you ANOTHER $10 since your email has already been credited with the $10. 
        <br /><br />Sorry about that, but the silver lining is you&#8217;ll be getting 
        awesome new recommendation hot off the Munch Ado presses. And if you haven&#8217;t 
        spent your $10, you can still login to <a href="http://munchado.com">MunchAdo.com</a> 
        (with your temporary password) and claim it! 
        <br /><br />For now though,<br />We must bid you Munch Ado</p>
    </td>
  </tr>
  