 <tr>
        <td><br>
			<p>Well, not officially at least. Not until you head over to our
				Facebook page and give us a little thumbs up, but that’s totally up
				to you. No pressure.</p>

			<p>In the meantime, you can enjoy tons of restaurant recommendations
				based on 10 customizable search options, or just your location or
				mood that’ll help you answer the preverbal question “What do I want
				to eat?”</p>
			<p>
				Soon, you’ll be enjoying your favorite foods and new cuisines at
				home, in the office and at the table all while you rack up points
				you can use towards your next meal or to treat your friends. Better
				yet, you can actually invite your friends to join Munch Ado and
				start up a group order! It’s a lot easier than the back and forth of
				an office lunch order if you ask us. Which you didn’t, but it’s
				true.
			</p>
			<p>And speaking of friends, have you followed us on Twitter yet? No?
				That’s okay… you’re only missing out on exclusive deals, awesome
				contests and Twitter games. We’re also pretty big on Pinterest so
				we’ve got that going for us too. And lest we forget about our blog,
				Instagram, Google+ and the multitude of other social media platforms
				we’re conquering.</p>
            <p><br />Until then though, <br />We must bid you Munch Ado<br /><br /></p>
	</tr>