<tr>
    <td>
      <p style="font-family:Arial, Helvetica, sans-serif; font-size:15px; color:#4b4b4b;padding-left:20px;padding-left:20px;padding-top:40px;padding-bottom:80px;padding-right:20px;line-height:20px;margin:0">
        Hey <strong style="color:fd7d01"><?php echo $this->username ;?></strong>,
        <br /><br />First, let us just say how happy we are you&#8217;re a member of the 
        Munch Ado family and watching you grow up over these past 
        <?php echo $this->joinTime; ?> has been a true gift. That&#8217;s why we 
        wanted to repay you with $10 off your next order.
        <br /><br />You can login to <a href="http://munchado.com">MunchAdo.com</a> 
        and redeem your coupon, or you can let us finish gushing over how much you&#8217;ve 
        matured. Remember when you forgot your password? Good times&#8230;or maybe 
        that was someone else. Anyway, we&#8217;re happy to see you making smart 
        decisions like getting more recommendations from "<?php echo $this->campaignName; ?>".
        <br /><br />Enough with all the mushy stuff though, you did a really great job 
        signing up for the latest from Munch Ado&#8217;s <?php echo $this->campaignName; ?>. 
        We&#8217;ll be sending you new recommendations every 
        time we update the list, but in the meantime $10 has been credited to your account so 
        order up something special. 
        <br /><br />For now though,<br />We must bid you Munch Ado</p>
    </td>
  </tr>