<tr>
    <td><br>
      <p style="font-size:16px;">Wah? </p>
      <p><strong><?php echo $this->name; ?></strong>, it looks like you've canceled your pre-scheduled order from <strong><?php echo $this->restaurant_name ;?></strong> on <strong><?php echo $this->timetodelivery; ?></strong>... <br>
<br>

<!-- Here is your new order:


<br>
<br>

      
      <table width="630" height="161" border="0" cellpadding="0" cellspacing="0" bgcolor="#ececec" style="margin-top:10px;">
        <tr>
    <td width="25" height="20"></td>
    <td width="309"></td>
    <td width="81"></td>
    <td width="217"></td>
    <td width="25"></td>
  </tr>
  <tr>
    <td height="125">&nbsp;</td>
    <td>
            <table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-size:12px;">
                  <tr>
                    <td height="25" align="left" valign="top" style="color:#666666;">Order Type: <span style="color:#666666;"><strong>Individual Delivery</strong></span> </td>
                  </tr>
                  <tr>
                       <td height="25" align="left" valign="top" style="color:#666666;">Deliver to: <span style="color:#666666;"><strong>245 5th Avenue Suite 1002, New York, NY 10016 - 11001</strong></span> </td>
                  </tr>
                  <tr>
                     <td height="25" align="left" valign="top" style="color:#666666;">Time of Order: <span style="color:#666666;"><strong>Tue 30, Jan, 2013 at 5:30PM</strong></span> </td>
                  </tr>
                    <td height="25" align="left" valign="top" style="color:#666666;">Time to Delivery: <span style="color:#666666;"><strong>Tue 30, Jan, 2013 at 7:30PM</strong></span> </td>
                  </tr>
                  
            </table>
            
            <table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-size:12px;">
                      <tr>
                    <td height="5" colspan="3" align="left" valign="top"></td>
                  </tr>
                  <tr>
                    <td height="13" colspan="3" align="left" valign="top" style="color:#666666;"><img src="#template_img_path#border.png" width="309" height="1" /></td>
                  </tr>
           
                  <tr>
                    <td height="35" colspan="3" align="left" valign="top" style="color:#666666; font-size:14px"><strong>Your Order</strong></td>
                  </tr>
                    <tr>
                      <td width="49%" height="25" align="left" valign="top" style="color:#666666;"><strong>Caesar salad</strong></td>
                      <td width="23%" align="center" valign="top" style="color:#666666;"><strong>1</strong></td>
                      <td width="28%" align="right" valign="top" style="color:#666666; font-size:14px"><strong>$5.95</strong></td>
                    </tr>
                    <tr>
                      <td height="25" colspan="3" align="left" valign="top" style="color:#666666;"><em>Lorem ipsum dolor sit emet - description about the dish
Lorolor sit emet - descem ipsum dription em ipsum. um
dolor sit emet - description about the dish Lorolor sit emet
descem ipsum dription em ipsum.</em></td>
                    </tr>
                   
            </table>

    </td>
    <td>&nbsp;</td>
    <td bgcolor="#FFFFFF">
		
    	<table width="83%" height="108" border="0" cellpadding="0" cellspacing="0" >
  <tr>
    <td>&nbsp;</td>
    <td colspan="3" align="right" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
    <td width="6%" rowspan="6">&nbsp;</td>
  </tr>
  <tr>
    <td width="7%">&nbsp;</td>
    <td width="46%" align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Subtotal:</td>
    <td width="2%" align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
    <td width="35%" align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$10.90</strong></td>
    </tr>
  <tr>
    <td width="7%">&nbsp;</td>
    <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Delivery:</td>
    <td  align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
    <td width="35%" align="left" valign="top" style="font-size:12px; color:#666666;"><strong>FREE</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Tax:</td>
    <td align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
    <td align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$0.75</strong></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Tip Amount:</td>
    <td align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
    <td align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$2.00</strong></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Total:</td>
    <td align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
    <td align="left" valign="top" style="font-size:12px; color:#ff8208;"><strong>$13.65</strong></td>
    </tr>
      <tr>
    <td height="15" colspan="5"></td>
    </tr>
  <tr>
    <td colspan="5"><img src="#template_img_path#whitebdr.gif" /></td>
    </tr>
  <tr>
    <td colspan="5">&nbsp;</td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td colspan="3" align="left" valign="top" style="font-size:12px; color:#666666;"><strong>Payment:</strong><br>
      Credit Card<br>
      VISA (XXXX-XXXX-XXXX-1234 /<br>
      Exp: 04/14)</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="5">&nbsp;</td>
    </tr>
        </table>
    
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td height="20"></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table><br> -->
</p>
<p>Hopefully that's what you meant to do. If you'd like to re-establish the order just sign back into <a style="color:#ff8208; text-decoration:none;" href="<?php echo $this->host_name;?>" target="_blank"><strong>Munch Ado</strong></a>
  and <strong>reclaim your points by reordering!</strong><br>
    </p>
    <p><br />For now though,<br />We must bid you Munch Ado<br /><br /></p>
    </td>
  </tr>
  <tr><td style="padding-bottom:30px;padding-top:20px;color:#867f7c;font-size:14px;font-family:arial;font-style:italic;">If you have any further questions feel free to email us (The Munch Ado Crew) at <a href="mailto:wecare@munchado.com" style="text-decoration:none;color: #867f7c; font-weight: bold; outline: none;">WeCare@MunchAdo.com</a> or give us a call at <a href="tel:1-888-345-1303" style="font-weight:bold;color:#867f7c;text-decoration:none">1-888-345-1303</a>.</td></tr>