<tr>
    <td><br>
      <p style="font-size:16px;">Hey <strong><?php echo $this->ownername ;?></strong>,</p>
      <p>We're sorry to say <strong><?php echo $this->username ;?></strong> has canceled reservation <strong>#<?php echo $this->receiptNo ;?></strong> for <strong><?php echo $this->numberOfPeople ;?></strong> people on <strong><?php echo $this->reservationDate ;?></strong> at <strong><?php echo $this->reservationtime ;?></strong>.<br>
      We're sure the spot will fill back up quickly.</p>
      <p><br>
      </p>
     <br>
     <p>Best,<br/>
      <em>The Munch Ado Crew </em></p>
     
      <br></td>
  </tr>
