<tr>
    <td><br>
        <p style="font-size: 16px;">
            Hey <strong><?php echo $this->ownername; ?></strong>,
        </p>
        <p>
            It&#39;s the moment of truth. <strong><?php echo $this->username; ?></strong>
            has posted a review. <a
                style="color: #ff8208; text-decoration: none;"
                href="<?php echo $this->dashboard_url; ?>"><strong>Read it
                    here</strong></a>.<br> You&#39;re welcome to respond to <strong><?php echo $this->username; ?>&#39;s
            </strong> review directly, although we urge you to use a proactive
            approach to negative reviews.
        </p>
        <p>
            If you have any questions, feel free to contact us at
            1-888-345-1303.<br> <br> <br>
        </p>
        <br>
        <p>
            Best,<br /> <em>The Munch Ado Crew </em>
        </p> <br> <br></td>
</tr>