<tr>
		<td><br>
			<p style="font-size: 16px;">
				Hey <strong><?php echo $this->ownername;?></strong>,
			</p>
			<p>
				<strong><?php echo $this->username;?></strong> has updated
				reservation <strong><?php echo $this->receiptNo;?></strong> His new
				reservation is for <strong><?php echo $this->numberOfPeople;?></strong> people
				on <strong><?php echo $this->reservationDate;?></strong> at <strong><?php echo $this->reservationtime;?></strong>.<br>
				We wish we were <strong><?php echo $this->username;?>!</strong>
			</p>
			<p>
				<br>
			</p>
            <br>
			<p>
				Best,<br /> <em>The Munch Ado Crew </em>
			</p> <br></td>
	</tr>

