<table align="left" cellpadding="0" cellspacing="0"   style="border-collapse: collapse; width:100%;  font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px;">	
    <tr><td height="56"></td></tr>
    <?php if($this->referral){?>
    
    
    <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px; font-weight:bold">Dear <?php echo $this->touser;?>,</td></tr>
    <tr><td height="18"></td></tr>
    <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px; line-height:24px">
    Your friend <span style="font-weight:bold"><?php echo $this->fromuser;?></span> has shared an interesting career opportunity with you, please click on the link below to read more about it.
      
    <tr><td height="28"></td></tr>
    <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px; font-weight:bold"><?php echo $this->careerlink;?></td></tr>
    
    
    <?php } else{?>
    
    
    <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px; font-weight:bold">Dear HR,</td></tr>
    <tr><td height="18"></td></tr>
    <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px; line-height:24px">You have received an application for <span style="font-weight:bold"><?php echo $this->jobTitle;?></span> User Experience from <span style="font-weight:bold"><?php echo $username?></span>.</td></tr>
    
    <?php if($this->portfoliolink){ ?>
    <tr><td height="28"></td></tr>
    <tr><td style="border-collapse: collapse; font-family:Arial, Helvetica, sans-serif; border:0px !important; font-size:16px; font-weight:bold">Portfolio Link : &nbsp;&nbsp;&nbsp; <a href="<?php echo $this->portfoliolink;?>" style="text-decoration:none; font-weight:normal; color:#cd2455" target="_blank"><?php echo $this->portfoliolink;?> </a></td></tr>
    <?php } ?>
    <?php } ?>
    <tr><td height="98"></td></tr>
</table> 