  <tr>
    <td height="75">We just wanted to let you know <strong><?php echo $this->restaurantName;?> </strong>is telling us they've delivered your order for <?php echo $this->timeOfOrder;?> .</td>
  </tr>
  <tr>
    <td valign="top" bgcolor="#ECECEC"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="3%" valign="top">&nbsp;</td>
        <td width="50%" valign="top">&nbsp;</td>
        <td width="10%" valign="top">&nbsp;</td>
        <td valign="top">&nbsp;</td>
        <td width="3%" valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
        <td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-size:12px;">
          <tr>
            <td height="25" align="left" valign="top" style="color:#666666;">Order Type: <strong><?php echo $this->orderType;?></strong></td>
          </tr>
          <tr>
            <td height="25" align="left" valign="top" style="color:#666666;">Delivery to: <strong><?php echo $this->address;?></strong></td>
          </tr>
          <tr>
            <td height="25" align="left" valign="top" style="color:#666666;">Time of Order: <strong><?php echo $this->timeOfOrder;?></strong></td>
          </tr>
          <tr>
            <td height="25" align="left" valign="top" style="color:#666666;">Time to Delivery: <strong><?php echo $this->timeOfDelivery;?></strong></td>
          </tr>
          <tr>
            <td align="left" valign="top" style="color:#666666;">&nbsp;</td>
          </tr>
          <tr>
            <td align="left" valign="top" style="color:#666666;"><table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-size:12px;">
              <tr>
                <td height="5" colspan="3" align="left" valign="top"></td>
              </tr>
              <tr>
                <td height="13" colspan="3" align="left" valign="top" style="color:#666666;"><img src="<?php echo TEMPLATE_IMG_PATH.'border.png' ;?>" width="309" height="1" /></td>
              </tr>
              <tr>
                <td height="35" colspan="3" align="left" valign="top" style="color:#666666; font-size:14px"><strong>Your Order</strong></td>
              </tr>
              <?php echo $this->orderData;?>
            </table></td>
          </tr>
        </table></td>
        <td valign="top">&nbsp;</td>
        <td valign="top" bgcolor="#FFFFFF"><table width="100%" height="108" border="0" cellpadding="0" cellspacing="0" >
          <tr>
            <td>&nbsp;</td>
            <td colspan="3" align="right" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
            <td width="6%" rowspan="6">&nbsp;</td>
          </tr>
          <tr>
            <td width="7%">&nbsp;</td>
            <td width="46%" align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Subtotal:</td>
            <td width="2%" align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
            <td width="35%" align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$<?php echo $this->subtotal;?></strong></td>
          </tr>
          <tr>
            <td width="7%">&nbsp;</td>
            <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Delivery:</td>
            <td  align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
            <td width="35%" align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$<?php echo $this->deliveryCharge;?></strong></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Tax:</td>
            <td align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
            <td align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$<?php echo $this->tax;?></strong></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Tip Amount:</td>
            <td align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
            <td align="left" valign="top" style="font-size:12px; color:#666666;"><strong>$<?php echo $this->tipAmount;?></strong></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td align="right" valign="top" style="font-size:12px; color:#8f8f8f;">Total:</td>
            <td align="left" valign="top" style="font-size:12px; color:#666666;">&nbsp;</td>
            <td align="left" valign="top" style="font-size:12px; color:#ff8208;"><strong>$<?php echo $this->total;?></strong></td>
          </tr>
          <tr>
            <td height="15" colspan="5"></td>
          </tr>
          <tr>
            <td colspan="5"><img src="<?php echo TEMPLATE_IMG_PATH.'whitebdr.gif' ;?>" /></td>
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td colspan="3" align="left" valign="top" style="font-size:12px; color:#666666;"><strong>Payment:</strong><br />
              Credit Card<br />
              <?php echo $this->cardType;?> (XXXX-XXXX-XXXX-<?php echo $this->cardNo;?> /<br />
              Exp: <?php echo $this->expiredOn;?>)</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
        </table></td>
        <td valign="top">&nbsp;</td>
      </tr>
      <tr>
        <td valign="top">&nbsp;</td>
        <td valign="top">&nbsp;</td>
        <td valign="top">&nbsp;</td>
        <td valign="top">&nbsp;</td>
        <td valign="top">&nbsp;</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="75">Hopefully, they delivered it to you and not the B in Apartment 23. If not, let us know (email, call etc.) and we'll yell at them on your behalf.</td>
  </tr>
  <tr>
    <td valign="top"><table width="630" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td style="font-size:13px; color:#666666;">For now though,</td>
      </tr>
      <tr>
        <td style="font-size:13px; color:#666666;">We must bid you Munch Ado</td>
      </tr>
    </table></td>
  </tr>
