	<tr>
		<td><br>
			<p style="font-size: 16px;">
				Hey,<br>
			</p>
			<p style="font-size: 16px;">
				A new order has been scheduled.<br> <br>
			</p>

			<table width="630" height="161" border="0" cellpadding="0"
				cellspacing="0" bgcolor="#ececec" style="margin-top: 10px;">
				<tr>
					<td width="25">&nbsp;</td>
					<td width="309">&nbsp;</td>
					<td width="81">&nbsp;</td>
					<td width="217">&nbsp;</td>
					<td width="25">&nbsp;</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<table width="100%" border="0" cellspacing="0" cellpadding="0"
							style="font-size: 12px;">
							<tr>
								<td height="25" align="left" valign="top"
									style="color: #666666;">Order Type: <strong><?php echo $this->orderType; ?></strong>
								</td>
							</tr>
							<tr>
								<td height="25" align="left" valign="top"
									style="color: #666666;">Receipt number: <strong><?php echo $this->receiptNo;?></strong>
								</td>
							</tr>
							<tr>
								<td height="25" align="left" valign="top"
									style="color: #666666;">Time of Order: <strong><?php echo $this->timeOfOrder;?></strong>
								</td>
							</tr>
							<tr>
								<td height="25" align="left" valign="top"
									style="color: #666666;">Time of Delivery: <strong><?php echo $this->timeOfDelivery; ?></strong>
								</td>
							</tr>
							<?php if(!empty($this->specialInstructions)){ ?>
							<tr>
								<td height="25" align="left" valign="top"
									style="color: #666666;">Special Instructions: <br /> <i><?php echo $this->specialInstructions; ?></i>
								</td>
							</tr>
                         <?php }?>
						</table>

						<table width="100%" border="0" cellspacing="0" cellpadding="0"
							style="font-size: 12px;">
							<tr>
								<td colspan="3" align="left" style="color: #666666;"><img
									src="<?php echo TEMPLATE_IMG_PATH.'border.png';?>" width="309" height="1" /></td>
							</tr>                
                  <?php echo $this->orderData;?>


            </table>

					</td>
					<td>&nbsp;</td>
					<td valign="top">

						<table width="217" border="0" cellpadding="0" cellspacing="0"
							bgcolor="#FFFFFF">
							<tr>
								<td>&nbsp;</td>
								<td colspan="3" align="right" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td width="6%" rowspan="6">&nbsp;</td>
							</tr>
							<tr>
								<td width="7%">&nbsp;</td>
								<td width="46%" align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;">Subtotal:</td>
								<td width="2%" align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td width="35%" align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong><?php echo '$'.$this->subtotal;?></strong></td>
							</tr>
							<?php if($this->dealDiscount!=0){?>
							<tr>
								<td width="7%">&nbsp;</td>
								<td width="46%" align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;">Deal Discount:</td>
								<td width="2%" align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td width="35%" align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong><?php echo '$'.$this->dealDiscount;?></strong></td>
							</tr>
                                                        <?php } ?>
                                                        
							<?php if($this->deliveryCharge !=0){?>
							<tr>
								<td width="7%">&nbsp;</td>
								<td align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;">Delivery:</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td width="35%" align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong>$<?php echo $this->deliveryCharge; ?></strong></td>
							</tr>
							<?php }?>
							<tr>
								<td>&nbsp;</td>
								<td align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;">Tax:</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong><?php echo '$'.$this->tax;?></strong></td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;">Tip Amount:</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong><?php echo '$'.$this->tipAmount;?></strong></td>
							</tr>
                                                        <?php if($this->promocodeDiscount!=0){?>
                                                        <tr>
								<td width="7%">&nbsp;</td>
								<td width="46%" align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;" nowrap>Promo code Discount:</td>
								<td width="2%" align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td width="35%" align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong><?php echo '$'.$this->promocodeDiscount;?></strong></td>
							</tr>
							<?php } ?>
							<tr>
								<td>&nbsp;</td>
								<td align="right" valign="top"
									style="font-size: 12px; color: #8f8f8f;">Total:</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #666666;">&nbsp;</td>
								<td align="left" valign="top"
									style="font-size: 12px; color: #ff8208;"><strong><?php echo '$'.$this->total;?></strong></td>
							</tr>
							<tr>
								<td height="15" colspan="5"></td>
							</tr>
							<tr>
								<td colspan="5"><img src="<?php echo TEMPLATE_IMG_PATH.'whitebdr.gif';?>" /></td>
							</tr>
							<tr>
								<td colspan="5">&nbsp;</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
								<td colspan="3" align="left" valign="top"
									style="font-size: 12px; color: #666666;"><strong>Payment:</strong><br>
									Credit Card<br>
      <?php echo $this->cardType; ?> (XXXX-XXXX-XXXX-<?php echo $this->cardNo;?> /<br>
      Exp: <?php echo $this->expiredOn?>)</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td colspan="5">&nbsp;</td>
							</tr>
						</table>

					</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td height="20"></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</table>
	 <br></td>
	</tr>
